apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-deployment
  labels:
    role: app
spec:
  replicas: 2
  selector:
    matchLabels:
      role: app
  template:
    metadata:
      labels:
        role: app
    spec:
      containers:
      - name: app
        image: "13.233.184.68:8123/hello-world-2.1.0"
        resources:
          requests:
            cpu: 10m
      imagePullSecrets:
       - name: regsecret

apiVersion: v1
kind: Service
metadata:
  name: example-svc
spec:
  selector:
    role: app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8443
  type: NodePort
